---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "rrst.fullname" . }}-service-config
data:
  NODE_ENV: "{{ $.Values.environment }}"
  {{- $schemes := list "http" }}
  {{- if .Values.global.gateway.tls }}
  {{-   $schemes = ternary (list "https") (list "http" "https") .Values.global.gateway.hsts }}
  {{- end }}
  {{- $hosts := concat (dig "corsHosts" list ($.Values.global | default dict)) (list $.Values.host) }}
  {{- $origins := list }}
  {{- range $host := $hosts }}
  {{-   range $scheme := $schemes }}
  {{-     $origins = append $origins (printf "%s://%s" $scheme (include "rrst.render" (dict "value" $host "context" $))) }}
  {{-   end }}
  {{- end }}
  cors__origins: {{ $origins | toJson | quote }}
  trusted_proxies: {{ $.Values.global.trustedProxies | default list | toJson | quote }}
  {{- range $k, $v := $.Values.service.config }}
  {{- if kindIs "string" $v }}
  {{ $k }}: {{ tpl $v $ | quote }}
  {{- else if kindIs "slice" $v }}
  {{ $k }}: {{ $v | toJson | quote }}
  {{- else if kindIs "map" $v }}
  {{ $k }}: {{ $v | toJson | quote }}
  {{- else }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
