{{- if and $.Values.gateway.tls (ne (include "rrst.render" (dict "value" $.Values.host "context" $)) "localhost") (not (contains ".local" (include "rrst.render" (dict "value" $.Values.host "context" $)))) }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ (include "rrst.render" (dict "value" $.Values.host "context" $)) }}
  namespace: {{ $.Release.Namespace }}
spec:
  secretName: {{ (include "rrst.render" (dict "value" $.Values.host "context" $)) }}-tls-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - RapidREST
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: {{ (include "rrst.render" (dict "value" $.Values.host "context" $)) }}
  isCA: false
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 384
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  - {{ (include "rrst.render" (dict "value" $.Values.host "context" $)) }}
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
{{- end }}